// For generation use:
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/keeper.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_PAIR DataType = 0
	DataType_TEXT DataType = 1
	DataType_FILE DataType = 2
	DataType_CARD DataType = 3
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "PAIR",
		1: "TEXT",
		2: "FILE",
		3: "CARD",
	}
	DataType_value = map[string]int32{
		"PAIR": 0,
		"TEXT": 1,
		"FILE": 2,
		"CARD": 3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_keeper_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_proto_keeper_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{0}
}

type Spec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           DataType `protobuf:"varint,2,opt,name=type,proto3,enum=keeper.DataType" json:"type,omitempty"`
	Tytle          string   `protobuf:"bytes,3,opt,name=tytle,proto3" json:"tytle,omitempty"`
	DataSize       int64    `protobuf:"varint,4,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
	HasDescription bool     `protobuf:"varint,5,opt,name=has_description,json=hasDescription,proto3" json:"has_description,omitempty"`
}

func (x *Spec) Reset() {
	*x = Spec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *Spec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spec) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_PAIR
}

func (x *Spec) GetTytle() string {
	if x != nil {
		return x.Tytle
	}
	return ""
}

func (x *Spec) GetDataSize() int64 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

func (x *Spec) GetHasDescription() bool {
	if x != nil {
		return x.HasDescription
	}
	return false
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        DataType `protobuf:"varint,1,opt,name=type,proto3,enum=keeper.DataType" json:"type,omitempty"`
	Title       string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data        []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Description []byte   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_PAIR
}

func (x *Record) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Record) GetDescription() []byte {
	if x != nil {
		return x.Description
	}
	return nil
}

type GetSpecsOfTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type DataType `protobuf:"varint,1,opt,name=type,proto3,enum=keeper.DataType" json:"type,omitempty"`
}

func (x *GetSpecsOfTypeRequest) Reset() {
	*x = GetSpecsOfTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpecsOfTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecsOfTypeRequest) ProtoMessage() {}

func (x *GetSpecsOfTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecsOfTypeRequest.ProtoReflect.Descriptor instead.
func (*GetSpecsOfTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpecsOfTypeRequest) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_PAIR
}

type Specs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Specs []*Spec `protobuf:"bytes,1,rep,name=specs,proto3" json:"specs,omitempty"`
}

func (x *Specs) Reset() {
	*x = Specs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specs) ProtoMessage() {}

func (x *Specs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specs.ProtoReflect.Descriptor instead.
func (*Specs) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *Specs) GetSpecs() []*Spec {
	if x != nil {
		return x.Specs
	}
	return nil
}

type DataSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataSize uint64 `protobuf:"varint,2,opt,name=data_size,json=dataSize,proto3" json:"data_size,omitempty"`
}

func (x *DataSpec) Reset() {
	*x = DataSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSpec) ProtoMessage() {}

func (x *DataSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSpec.ProtoReflect.Descriptor instead.
func (*DataSpec) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *DataSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataSpec) GetDataSize() uint64 {
	if x != nil {
		return x.DataSize
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RecordID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RecordID) Reset() {
	*x = RecordID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordID) ProtoMessage() {}

func (x *RecordID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordID.ProtoReflect.Descriptor instead.
func (*RecordID) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *RecordID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSpecsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSpecsRequest) Reset() {
	*x = GetSpecsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keeper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSpecsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecsRequest) ProtoMessage() {}

func (x *GetSpecsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecsRequest.ProtoReflect.Descriptor instead.
func (*GetSpecsRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{7}
}

var File_proto_keeper_proto protoreflect.FileDescriptor

var file_proto_keeper_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x22, 0x98, 0x01, 0x0a,
	0x04, 0x53, 0x70, 0x65, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x79, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x74, 0x6c,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x68, 0x61, 0x73, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x68, 0x61, 0x73, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7a, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x73, 0x4f,
	0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x2b, 0x0a, 0x05, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x73,
	0x70, 0x65, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x52, 0x05, 0x73, 0x70, 0x65, 0x63, 0x73, 0x22,
	0x37, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x65, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x1a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x44,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2a, 0x32, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x41, 0x49, 0x52, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58,
	0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x03, 0x32, 0x88, 0x02, 0x0a, 0x06, 0x4b, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x12, 0x32, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x17,
	0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x3e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65,
	0x63, 0x73, 0x4f, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x73, 0x4f, 0x66, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x70, 0x65, 0x63, 0x1a, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x30, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x49, 0x44, 0x1a, 0x0c, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x0e, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x1a, 0x10, 0x2e, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x44, 0x42, 0x12, 0x5a, 0x10, 0x67, 0x6f, 0x70, 0x68, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_keeper_proto_rawDescOnce sync.Once
	file_proto_keeper_proto_rawDescData = file_proto_keeper_proto_rawDesc
)

func file_proto_keeper_proto_rawDescGZIP() []byte {
	file_proto_keeper_proto_rawDescOnce.Do(func() {
		file_proto_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_keeper_proto_rawDescData)
	})
	return file_proto_keeper_proto_rawDescData
}

var file_proto_keeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_keeper_proto_goTypes = []interface{}{
	(DataType)(0),                 // 0: keeper.DataType
	(*Spec)(nil),                  // 1: keeper.Spec
	(*Record)(nil),                // 2: keeper.Record
	(*GetSpecsOfTypeRequest)(nil), // 3: keeper.GetSpecsOfTypeRequest
	(*Specs)(nil),                 // 4: keeper.Specs
	(*DataSpec)(nil),              // 5: keeper.DataSpec
	(*Data)(nil),                  // 6: keeper.Data
	(*RecordID)(nil),              // 7: keeper.RecordID
	(*GetSpecsRequest)(nil),       // 8: keeper.GetSpecsRequest
}
var file_proto_keeper_proto_depIdxs = []int32{
	0, // 0: keeper.Spec.type:type_name -> keeper.DataType
	0, // 1: keeper.Record.type:type_name -> keeper.DataType
	0, // 2: keeper.GetSpecsOfTypeRequest.type:type_name -> keeper.DataType
	1, // 3: keeper.Specs.specs:type_name -> keeper.Spec
	8, // 4: keeper.Keeper.GetSpecs:input_type -> keeper.GetSpecsRequest
	3, // 5: keeper.Keeper.GetSpecsOfType:input_type -> keeper.GetSpecsOfTypeRequest
	5, // 6: keeper.Keeper.GetData:input_type -> keeper.DataSpec
	7, // 7: keeper.Keeper.GetDescription:input_type -> keeper.RecordID
	2, // 8: keeper.Keeper.AddRecord:input_type -> keeper.Record
	4, // 9: keeper.Keeper.GetSpecs:output_type -> keeper.Specs
	4, // 10: keeper.Keeper.GetSpecsOfType:output_type -> keeper.Specs
	6, // 11: keeper.Keeper.GetData:output_type -> keeper.Data
	6, // 12: keeper.Keeper.GetDescription:output_type -> keeper.Data
	7, // 13: keeper.Keeper.AddRecord:output_type -> keeper.RecordID
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_keeper_proto_init() }
func file_proto_keeper_proto_init() {
	if File_proto_keeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_keeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keeper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpecsOfTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keeper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keeper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keeper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keeper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keeper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSpecsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_keeper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_keeper_proto_goTypes,
		DependencyIndexes: file_proto_keeper_proto_depIdxs,
		EnumInfos:         file_proto_keeper_proto_enumTypes,
		MessageInfos:      file_proto_keeper_proto_msgTypes,
	}.Build()
	File_proto_keeper_proto = out.File
	file_proto_keeper_proto_rawDesc = nil
	file_proto_keeper_proto_goTypes = nil
	file_proto_keeper_proto_depIdxs = nil
}
